name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/home-5.png
    - assets/page-1/images/home-2.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/image-16-32B.png
    - assets/page-1/images/home-2-45h.png
    - assets/page-1/images/image-16-yfq.png
    - assets/page-1/images/heart-1.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/group-16.png
    - assets/page-1/images/heart-1-iyR.png
    - assets/page-1/images/fire-1.png
    - assets/page-1/images/auto-group-fh8f.png
    - assets/page-1/images/heart-1-KZV.png
    - assets/page-1/images/heart-4.png
    - assets/page-1/images/heart-2-2.png
    - assets/page-1/images/heart-1-ptj.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/magnifying-glass-1.png
    - assets/page-1/images/auto-group-dj6p.png
    - assets/page-1/images/home-4.png
    - assets/page-1/images/auto-group-nelb.png
    - assets/page-1/images/image-17.png
    - assets/page-1/images/clock-4.png
    - assets/page-1/images/heart-1-wWT.png
    - assets/page-1/images/fire-4.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/image-19-D2j.png
    - assets/page-1/images/image-19-kVq.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/clock-3.png
    - assets/page-1/images/image-19-8ef.png
    - assets/page-1/images/image-18.png
    - assets/page-1/images/home-2-13Z.png
    - assets/page-1/images/image-19-1dD.png
    - assets/page-1/images/image-19-xoM.png
    - assets/page-1/images/image-19-8Sw.png
    - assets/page-1/images/image-19-SiX.png
    - assets/page-1/images/image-19-xw5.png
    - assets/page-1/images/clock-2.png
    - assets/page-1/images/heart-1-QLT.png
    - assets/page-1/images/image-19-Qr7.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/home-2-rtT.png
    - assets/page-1/images/rectangle-6-bg.png
    - assets/page-1/images/home-2-m4w.png
    - assets/page-1/images/heart-2-4.png
    - assets/page-1/images/magnifying-glass-1-HCw.png
    - assets/page-1/images/fire-3.png
    - assets/page-1/images/rectangle-7-bg.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/image-17-6YK.png
    - assets/page-1/images/home-2-GLK.png
    - assets/page-1/images/rectangle-5.png
    - assets/page-1/images/rectangle-5-bg.png
    - assets/page-1/images/home-2-GRy.png
    - assets/page-1/images/home-2-dpF.png
    - assets/page-1/images/home-2-SDZ.png
    - assets/page-1/images/heart-1-h9V.png
    - assets/page-1/images/heart-1-T8f.png
    - assets/page-1/images/image-20-zuH.png
    - assets/page-1/images/home-2-3Ns.png
    - assets/page-1/images/home-2-6bM.png
    - assets/page-1/images/auto-group-duby.png
    - assets/page-1/images/rectangle-11-bg.png
    - assets/page-1/images/rectangle-22.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/image-20-Cb5.png
    - assets/page-1/images/fire-2.png
    - assets/page-1/images/rectangle-11.png
    - assets/page-1/images/bookmark-1.png
    - assets/page-1/images/rectangle-26.png
    - assets/page-1/images/fire-1-eZR.png
    - assets/page-1/images/vector-27.png
    - assets/page-1/images/bookmark-1-f4X.png
    - assets/page-1/images/rectangle-7.png
    - assets/page-1/images/image-9-12T.png
    - assets/page-1/images/vector-26.png
    - assets/page-1/images/vector-23.png
    - assets/page-1/images/image-9-BoR.png
    - assets/page-1/images/home-2-wxw.png
    - assets/page-1/images/image-8-zhZ.png
    - assets/page-1/images/image-9-xPV.png
    - assets/page-1/images/bookmark-2.png
    - assets/page-1/images/home-2-K23.png
    - assets/page-1/images/home-2-a8K.png
    - assets/page-1/images/vector-25.png
    - assets/page-1/images/heart-1-upf.png
    - assets/page-1/images/heart-1-Ehq.png
    - assets/page-1/images/home-2-UAf.png
    - assets/page-1/images/heart-2-4-zq9.png
    - assets/page-1/images/rectangle-5-aVq.png
    - assets/page-1/images/clock-2-VKH.png
    - assets/page-1/images/heart-2-1.png
    - assets/page-1/images/clock-4-cMH.png
    - assets/page-1/images/bookmark-3.png
    - assets/page-1/images/ellipse-5.png
    - assets/page-1/images/heart-1-MFZ.png
    - assets/page-1/images/rectangle-11-gZH.png
    - assets/page-1/images/clock-1.png
    - assets/page-1/images/heart-3.png
    - assets/page-1/images/clock-1-UWw.png
    - assets/page-1/images/heart-2-5.png
    - assets/page-1/images/heart-1-pdy.png
    - assets/page-1/images/heart-1-JgB.png
    - assets/page-1/images/image-9-Sf5.png
    - assets/page-1/images/image-20-Nou.png
    - assets/page-1/images/heart-1-SXV.png
    - assets/page-1/images/rectangle-6.png
    - assets/page-1/images/clock-3-biK.png
    - assets/page-1/images/fire-2-NJP.png
    - assets/page-1/images/heart-1-fEB.png
    - assets/page-1/images/heart-1-PtF.png
    - assets/page-1/images/heart-2-3.png
    - assets/page-1/images/home-2-1wy.png
    - assets/page-1/images/home-2-Z6K.png
    - assets/page-1/images/ellipse-2.png
    - assets/page-1/images/image-19-HXq.png
    - assets/page-1/images/image-9-Gzw.png
    - assets/page-1/images/home-2-XQF.png
    - assets/page-1/images/heart-1-pk3.png
    - assets/page-1/images/fire-3-6D1.png
    - assets/page-1/images/fire-4-XMm.png
    - assets/page-1/images/heart-2-2-2u9.png
    - assets/page-1/images/heart-1-79D.png
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/image-13-dEs.png
    - assets/page-1/images/heart-2-3-4Ub.png
    - assets/page-1/images/image-13-4Ys.png
    - assets/page-1/images/image-9-zhR.png
    - assets/page-1/images/image-13-6Ef.png
    - assets/page-1/images/heart-1-37Z.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-24.png
    - assets/page-1/images/group.png
    - assets/page-1/images/group-15.png
    - assets/page-1/images/bookmark-1-k4K.png
    - assets/page-1/images/home-2-6VR.png
    - assets/page-1/images/vector-FbZ.png
    - assets/page-1/images/vector-JGB.png
    - assets/page-1/images/vector-ybR.png
    - assets/page-1/images/vector-rMh.png
    - assets/page-1/images/image-9-1Ab.png
    - assets/page-1/images/image-20-6hR.png
    - assets/page-1/images/image-19-Rab.png
    - assets/page-1/images/ellipse-4.png
    - assets/page-1/images/ellipse-7.png
    - assets/page-1/images/group-12.png
    - assets/page-1/images/heart-2-6.png
    - assets/page-1/images/heart-2-3-tdR.png
    - assets/page-1/images/clock-5.png
    - assets/page-1/images/vector-2Gb.png
    - assets/page-1/images/auto-group-v4zf.png
    - assets/page-1/images/fire-3-1Vu.png
    - assets/page-1/images/auto-group-m6x3.png
    - assets/page-1/images/fire-6.png
    - assets/page-1/images/heart-2-4-ehR.png
    - assets/page-1/images/fire-1-hXh.png
    - assets/page-1/images/group-rRq.png
    - assets/page-1/images/clock-1-vYb.png
    - assets/page-1/images/magnifying-glass-1-uGP.png
    - assets/page-1/images/clock-6.png
    - assets/page-1/images/fire-4-XxP.png
    - assets/page-1/images/heart-2-5-LtT.png
    - assets/page-1/images/image-9-TjR.png
    - assets/page-1/images/home-2-J3d.png
    - assets/page-1/images/fire-5.png
    - assets/page-1/images/rectangle-22-po5.png
    - assets/page-1/images/clock-4-vYT.png
    - assets/page-1/images/heart-2-2-LAo.png
    - assets/page-1/images/bookmark-3-CWw.png
    - assets/page-1/images/fire-2-qkf.png
    - assets/page-1/images/rectangle-6-bg-9Kq.png
    - assets/page-1/images/clock-2-7XR.png
    - assets/page-1/images/image-19-gqH.png
    - assets/page-1/images/heart-2-4-T2b.png
    - assets/page-1/images/heart-1-if5.png
    - assets/page-1/images/heart-1-aFD.png
    - assets/page-1/images/rectangle-6-WGK.png
    - assets/page-1/images/rectangle-7-Ahh.png
    - assets/page-1/images/clock-3-i8s.png
    - assets/page-1/images/clock-1-fT9.png
    - assets/page-1/images/fire-1-DUf.png
    - assets/page-1/images/vector-PLP.png
    - assets/page-1/images/clock-4-LMy.png
    - assets/page-1/images/heart-1-dJT.png
    - assets/page-1/images/heart-2-1-T71.png
    - assets/page-1/images/fire-2-X8P.png
    - assets/page-1/images/heart-2-1-JTu.png
    - assets/page-1/images/image-9-a5H.png
    - assets/page-1/images/rectangle-7-bg-f5D.png
    - assets/page-1/images/rectangle-11-rTm.png
    - assets/page-1/images/image-19-3FH.png
    - assets/page-1/images/clock-3-NaP.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/fire-4-2o5.png
    - assets/page-1/images/clock-2-9sh.png
    - assets/page-1/images/rectangle-11-P71.png
    - assets/page-1/images/clock-1-cMh.png
    - assets/page-1/images/rectangle-5-kV1.png
    - assets/page-1/images/rectangle-19.png
    - assets/page-1/images/image-19-8VR.png
    - assets/page-1/images/home-2-gj5.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/rectangle-11-EvP.png
    - assets/page-1/images/heart-2-3-u2s.png
    - assets/page-1/images/fire-3-fpP.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-9-qnj.png
    - assets/page-1/images/heart-2-2-4eX.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/fire-1-MDm.png
    - assets/page-1/images/home-2-18w.png
    - assets/page-1/images/rectangle-5-pAw.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
